name: Push
description: Push image to fockerhub
inputs:
  username:
    description: "Dockerhub username"
    required: true
    default: ""
  password:
    description: "Dockerhub password"
    required: true
    default: ""
runs:
  using: composite
  steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Push to dockerhub
      run: docker push ${{ env.DOCKER_IMAGE_TAG_NAME }}
      shell: bash