name: Push
description: Push image to fockerhub
inputs:
  username:
    description: "Dockerhub username"
    required: true
    default: ""
  password:
    description: "Dockerhub password"
    required: true
    default: ""
runs:
  using: composite
  steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username:
        password:

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/academy

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: "{{defaultContext}}"
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}