name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Docker Build
      uses: TiagoAmar0/academy_cicd/.github/actions/maven_build@main
      with:
        tag: academy
        dockerfile_path: src/main/docker/Dockerfile.jvm

    - name: Push to Dockerhub
      uses: TiagoAmar0/academy_cicd/.github/actions/dockerhub_push@main
      with:
        username: $DOCKERHUB_USERNAME
        password: $DOCKERHUB_PASSWORD


#    - name: Build and push Docker image
#          uses: docker/build-push-action@v2
#          with:
#            context: "{{defaultContext}}"
#            push: true
#            tags: ${{ steps.meta.outputs.tags }}
#            labels: ${{ steps.meta.outputs.labels }}